# Generated by Django 5.2 on 2025-05-25 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayTao', models.DateTimeField()),
                ('NoiDung', models.TextField()),
                ('ThoiGianTao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BangHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.TextField()),
                ('NgayTao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BinhChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoTa', models.TextField()),
                ('TenTieuDe', models.CharField(max_length=255)),
                ('ThoiGianKetThucBC', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenPhong', models.CharField(max_length=255)),
                ('HinhAnhPhong', models.ImageField(blank=True, null=True, upload_to='phong_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CuocTroChuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiRiengTu', models.BooleanField(default=False)),
                ('TenNhom', models.CharField(blank=True, max_length=255, null=True)),
                ('HinhAnh', models.ImageField(upload_to='hinhanhavanhom/')),
                ('ThanhVien', models.ManyToManyField(related_name='Cuoc_tro_chuyen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anh', models.ImageField(upload_to='hinhanh/')),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.baiviet')),
            ],
        ),
        migrations.CreateModel(
            name='LuaChonBinhChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255)),
                ('binh_chon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.binhchon')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('AnhBia', models.ImageField(blank=True, null=True, upload_to='anhbia/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('MaPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.phongban')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.TextField()),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='BinhChonNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lua_chon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.luachonbinhchon')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='binhchon',
            name='MaNguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung'),
        ),
        migrations.CreateModel(
            name='BangTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.TextField()),
                ('NgayTao', models.DateTimeField()),
                ('MaHoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.banghoi')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung')),
            ],
        ),
        migrations.AddField(
            model_name='banghoi',
            name='MaNguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='MaNguoiDung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung'),
        ),
        migrations.CreateModel(
            name='BinhChonNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaBinhChon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.binhchon')),
                ('MaPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.phongban')),
            ],
            options={
                'unique_together': {('MaPhong', 'MaBinhChon')},
            },
        ),
        migrations.AddField(
            model_name='binhchon',
            name='PhongBans',
            field=models.ManyToManyField(related_name='BinhChons', through='MXHNBDN.BinhChonNhom', to='MXHNBDN.phongban'),
        ),
        migrations.CreateModel(
            name='TepDinhKem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tep', models.FileField(upload_to='tepdinhkem/')),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.baiviet')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhVienCuocTroChuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayGiaNhap', models.DateTimeField()),
                ('MaCuocTroChuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.cuoctrochuyen')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhanChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayTao', models.DateTimeField()),
                ('NoiDung', models.TextField(blank=True, null=True)),
                ('TepDinhKem', models.FileField(blank=True, null=True, upload_to='uploads/attachments/')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('MaCuocTroChuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.cuoctrochuyen')),
                ('NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LuotCamXuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('MaBaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.baiviet')),
                ('MaNguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MXHNBDN.nguoidung')),
            ],
            options={
                'unique_together': {('MaNguoiDung', 'MaBaiViet')},
            },
        ),
    ]
